### PR TITLE
static to shared for linux and mac

### LINKED ISSUE #4: static vs. shared lib
### Comment:

Hi, I noticed that the recipe builds the static library, rather than the shared as is common for conda: https://github.com/conda-forge/libecpint-feedstock/blob/main/recipe/meta.yaml#L31-L32 . Was there a technical reason for this, or would you be open to a switch to shared?

For reference, I've got an outline for a shared lib recipe https://github.com/psi4/psi4meta/blob/master/conda-recipes/libecpint/build.sh#L34-L50 

A few other unimplemented plans I've had for ecpint:
* turn off xml by default
* use cerf instead of vendoring Faddeeva https://github.com/robashaw/libecpint/blob/master/src/CMakeLists.txt#L56-L78
* spliting c and py packages
* (as mentioned) use shared instead of static libs

I haven't looked at libecpint recently, but I thought I'd inquire, and see what you think and need. Thanks!

### PR DESCRIPTION
**Pull request by loriab**
- [x] uses https://github.com/robashaw/libecpint/pull/59 that allows tests to build w/o c++14 error. builds and runs ctest in build phase.
- [x] switched libecpint and libFaddeeva from static to shared libraries. closes #4 
- [x] switched from GNU Makefiles to Ninja in prep for Windows
- [x] Python looks to be used for source generation and because there's a script packaged. For the former, I moved it out of host to `requirements/build` and restricted to one python since it's a dep that gets consumed by the build process. This cuts down on number of build variants. For the latter, parseecp.py, since it's a stray file packaged in share, I don't think it needs runtime python.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
> Looks good to me

Thanks, I think this is ready now.

**Pull request merged**
